// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3aiIMcvtb_6u8HDEYPvMCxaqsnjkDBQ',
    appId: '1:172740354558:web:2062f8fd7db345f30920af',
    messagingSenderId: '172740354558',
    projectId: 'ecommerceapp-2bddc',
    authDomain: 'ecommerceapp-2bddc.firebaseapp.com',
    storageBucket: 'ecommerceapp-2bddc.appspot.com',
    measurementId: 'G-6DF96MZLQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQpz0sROCEQdSydZyBR1Wl6dzAv-Ving',
    appId: '1:172740354558:android:653215326820d1220920af',
    messagingSenderId: '172740354558',
    projectId: 'ecommerceapp-2bddc',
    storageBucket: 'ecommerceapp-2bddc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK3aiIMcvtb_6u8HDEYPvMCxaqsnjkDBQ',
    appId: '1:172740354558:web:59b7151f36730bb10920af',
    messagingSenderId: '172740354558',
    projectId: 'ecommerceapp-2bddc',
    authDomain: 'ecommerceapp-2bddc.firebaseapp.com',
    storageBucket: 'ecommerceapp-2bddc.appspot.com',
    measurementId: 'G-9L1T0HP5RF',
  );
}
